travis:
  secure:
    BINSTAR_TOKEN: wSBhQt8/7UGn6/hQmolaQPeLwew36ttvdRrFuw615gYgF4iV14i2hu4hYZC1+volBVv6V3VJjzSWqQiyJkSf/pCbYY254KirNKyROn9GJWKIXgNaV24ZY6QUulryS9AVNDCBBnt8LKqY5uVf4ym/LXKGI6N7EAIWqPvffWE87azByYTdT3kegogxp/LrQNcY0hMltNIziVwD+EdlVqVPfzOlebU7LRGAgnyVYNpGuPtuDqn5vvbyLEk8uv0vl03zG6ETEKFBtCSBbEPHCKFddE3MxkfPEVfjqbEzixmbgh9FmJtsvibZOsTePp/cyzqy1cd/tNwNi/vFam3WOuHFQxhv1002700fkyr3SR2reh6wc41gW4XGu4ZRl1eyYr1D8So8MYsRolISkp8hMTbyxMw9zIbxOjZ6GfUYFcsG3XPCnCp/X0CJokEJszmpQ4UTLTKj3CV8J6o0wx2sI38g/BKJW+Awcbp/yAsvjTwy0vMS0aIbw0VOJMnTeVRhLSBoqatus61wwCcp1JMe4/mMIPbmFA4JcLBUz70liJDhrnkpTskaf9BNrER5gblS1xdVX7BFfu18DppHBLJ0wG8uQqTFKtN6S5yAFtA2CI/nWHwpRRxRpK43XHSMEoN+Jw7U3klG4WLy1D1ucyOgnty/ePaEuxJhEdLHNmKvfBWl320=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
