travis:
  secure:
    BINSTAR_TOKEN: pRXmJ7ObQ//XJCoUexGVC0LnTM/iplwi2Y+yVxmOqVl/qm271wRAn4YqfiOLtu4nKnHOARwJODrk3NsSavksvg8LmPkX+DpJSZSI7FiSu9x8s/Id4fVTM4A7VzMr1vULFtK0qP84LG/FzTfeUHrpX9jroNMrvxGANtUJ1ab/+foVypAsf6fjLdLbT9BQWPe0K4xTf+Tt0JZuGpWTS58Jn3VirqqMyG1f4cuGmCrH5/nXKVfg8oWsaEDQbZZiOKRrksgxwwRxCkArpLBh9G/U8vip2/pL0BpAxSNJG/7u9U28FUjE58vZaWrssE8BjuLzk78qq8EMabcA9nyTv6ck/J55vuiB+S0sTLUYRC4gYe1zdsMNPKSKH/4UqA8yeXELCV7WTOS7VzEn80tNWXl11zEzcdsnr5ffJef9I/NOFHWOc8fxGRp3g683E0R2oLayo8xybL41sKJLFsiU9FEXYpxwSP4n2PKl2c8S1h90ZuhlQsCI7Mi7rfMVspW31KKXs5gdOHh8EmitvSOnLjB5h3zpjyKf7fXOsTdO7Sq2lHLlhcbHsr3VLgep7C4+x1RkYGNg9+8HE4UkMzW8FUxQ/bmk446n4HeZDI5K+zUva/SzJfW3TAyQubLqhBT1kA8T4MV1kS3vZAUOouBwSGBztWVuaNrjdI+0DKmHlX5XWps=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
